/**
 * Regenerate the auto-generated documentation blocks from the single source of
 * truth (the code), so the tool table and client matrix can never drift:
 *
 *  - docs/reference/mcp.md      → AUTO-GENERATED:tools       (live MCP tool list)
 *  - docs/reference/clients.md  → AUTO-GENERATED:clients     (registry matrix)
 *                               → AUTO-GENERATED:quickstarts (per-host config block)
 *  - AGENTS.md                  → the standard config block for agent context
 *
 * Run via `npm run docs:tables`. Guarded against drift by a test.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createMcpServer } from '../src/mcp/server.js';
import { CartographyDB } from '../src/db.js';
import { defaultConfig } from '../src/types.js';
import { listClients, getClient, planInstall, defaultServerEntry } from '../src/installer/index.js';
import type { ResolveContext } from '../src/installer/index.js';

const root = resolve(import.meta.dirname, '..');

function replaceBlock(content: string, name: string, body: string): string {
  const re = new RegExp(`(<!-- AUTO-GENERATED:${name} START[^\\n]*-->\\n)[\\s\\S]*?(<!-- AUTO-GENERATED:${name} END -->)`);
  if (!re.test(content)) throw new Error(`marker ${name} not found`);
  return content.replace(re, `$1${body}\n$2`);
}

/** Live tool list from the running MCP server (single source of truth). */
async function toolTable(): Promise<string> {
  const db = new CartographyDB(':memory:');
  db.createSession('discover', defaultConfig());
  const server = createMcpServer({ db, discovery: async () => ({ nodes: 0, edges: 0 }) });
  const [ct, st] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: 'gen-docs', version: '1.0.0' });
  await Promise.all([client.connect(ct), server.connect(st)]);
  const { tools } = await client.listTools();
  await client.close();
  db.close();
  const rows = tools
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((t) => `| \`${t.name}\` | ${t.annotations?.readOnlyHint ? '✅' : '—'} | ${(t.description ?? '').split('\n')[0]} |`);
  return ['| Tool | Read-only | Description |', '| --- | --- | --- |', ...rows].join('\n');
}

function clientMatrix(): string {
  const rows = listClients().map((c) => `| \`${c.id}\` | ${c.label} | ${c.format} | ${c.note ?? ''} |`);
  return ['| id | Host | Format | Notes |', '| --- | --- | --- | --- |', ...rows].join('\n');
}

function quickstarts(): string {
  const ctx: ResolveContext = { scope: 'global', os: 'linux', home: '~', cwd: '.', env: {} };
  const entry = defaultServerEntry();
  const out: string[] = [];
  for (const c of listClients()) {
    const spec = getClient(c.id)!;
    const plan = planInstall(spec, ctx, { entry });
    const lang = plan.format === 'json' ? 'json' : plan.format;
    out.push(`### ${c.label} (\`${c.id}\`)`, '', `\`${plan.path}\``, '', '```' + lang, plan.after.trim(), '```', '');
  }
  return out.join('\n');
}

function agentsMd(): string {
  const entry = defaultServerEntry();
  const block = JSON.stringify({ mcpServers: { cartography: { command: entry.command, args: entry.args } } }, null, 2);
  return `# Working with Cartography

This project can use **Cartography** — an MCP server that maps the system landscape
(services, datastores, SaaS tools, dependencies) read-only.

## Enable it

\`\`\`json
${block}
\`\`\`

Or run \`datasynx-cartography install --client <id>\` (see \`list-clients\`).

## Use it

- Read \`cartography://graph/summary\` first — a low-token overview.
- Then drill in with \`query_infrastructure\`, \`get_dependencies\`, \`get_node\`.
- All tools are read-only; run \`run_discovery\` to (re)scan the local system.

<!-- Generated by \`npm run docs:tables\`; edit scripts/gen-docs.ts, not this file. -->
`;
}

export interface GeneratedDocs {
  mcpPath: string;
  mcp: string;
  clientsPath: string;
  clients: string;
  agentsPath: string;
  agents: string;
}

/** Pure: compute the regenerated file contents from the current sources. */
export async function buildDocs(): Promise<GeneratedDocs> {
  const mcpPath = resolve(root, 'docs/reference/mcp.md');
  const mcp = replaceBlock(readFileSync(mcpPath, 'utf8'), 'tools', await toolTable());

  const clientsPath = resolve(root, 'docs/reference/clients.md');
  let clients = readFileSync(clientsPath, 'utf8');
  clients = replaceBlock(clients, 'clients', clientMatrix());
  clients = replaceBlock(clients, 'quickstarts', quickstarts());

  return { mcpPath, mcp, clientsPath, clients, agentsPath: resolve(root, 'AGENTS.md'), agents: agentsMd() };
}

export async function generateDocs(): Promise<void> {
  const d = await buildDocs();
  writeFileSync(d.mcpPath, d.mcp);
  writeFileSync(d.clientsPath, d.clients);
  writeFileSync(d.agentsPath, d.agents);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generateDocs().then(() => console.log('✓ Regenerated tool table, client matrix, quickstarts, AGENTS.md'));
}
